import { EntCPL } from './EntCPL';
import { EntDailySheetTurn } from './EntDailySheetTurn';
import { EntDailySheetPagPro } from './EntDailySheetPagPro';
import { EntDailySheetPagCli } from './EntDailySheetPagCli';
import { EntDailySheetVenCli } from './EntDailySheetVenCli';
import { EntDailySheetSupport } from './EntDailySheetSupport';
import { EntAdvance } from './EntAdvance';
import { EntOtrosPagos } from './EntOtrosPagos';

export class EntDailySheet {
    ID: number;
    NUM: number;
    ID_ESTACION: number;
    FECHA: string;
    CREADO: string;
    TIPO: string;
    V_TOTAL: number;
    V_CANT: number;
    OI_LUBRICANTE: number;
    OI_SOAT_REF: string;
    OI_SOAT: number;
    OI_SOAT_COM: number;
    OI_SOAT_VEN: number;
    OI_SOAT_ANU: number;
    OI_SOAT_REEM: number;
    OI_PREMIO: number;
    OI_APROV_DET: string;
    OI_APROV: number;
    OI_PRESTAMO_LIQ: number;
    OI_CUSIANA: number;
    OI_PAG_CAR_CLI: number;
    OI_PAG_CAR_CLI_DAT: number;
    OI_PAG_ANT_CLI: number;
    OI_OTRO_DET: string;
    OI_OTRO: number;
    OI_PRESTAMO_DET: string;
    OI_PRESTAMO: number;
    OI_TOTAL: number;
    TOTAL_OI_VENTAS: number;
    FP_BONO_PUNTO: number;
    FP_BONO_CUMPLE: number;
    FP_BONO_SOAT: number;
    FP_CALIBRACION: number;
    FP_CLI_CRE: number;
    FP_CLI_ANT: number;
    FP_DATAFONO: number;
    FP_DESC: number;
    FP_DEV: number;
    FP_DONACION: number;
    FP_MANT: number;
    FP_PREST: number;
    FP_OTRO_DET: string;
    FP_OTRO: number;
    FP_TOTAL: number;
    TOTAL_EFEC_REC: number;
    CAJ_CUST_SALDO: number;
    DE_PROV: number; // Variable que acumula los pagos
    DE_REEM_CAJ_MEN_NUM: number;
    DE_REEM_CAJ_MEN: number;
    DE_SERV_PUB_DET: string;
    DE_SERV_PUB: number;
    DE_OTRO_DET: string;
    DE_OTRO: number;
    DE_TOTAL_EFE: number;
    DE_TOTAL: number;
    DE_ANT_PROV: EntAdvance[]; // Acumula los anticipos
    DE_ACUM_ANTICIPOS: number; // Monto Acumulado de los Anticipos disponibles
    DE_OTROS_PAGOS: EntOtrosPagos [];
    DE_ANTI_A_ELIMIN:  any[] = [];
    DE_OTROS_A_ELIMIN:  any[] = [];
    CB_LUBRI_DET: string;
    CB_LUBRI: number;
    CB_LIQ_DET: string;
    CB_LIQ: number;
    CB_GAS_DET: string;
    CB_GAS: number;
    CB_REC_CART_DET: string;
    CB_REC_CART: number;
    CB_SEG_EST_DET: string;
    CB_SEG_EST: number;
    CB_CUSIANA_DET: string;
    CB_CUSIANA: number;
    CB_TOTAL: number;
    SAL_FIN_CAJA: number;
    CAJA_GRAL_MEN: number;
    PLA_DIA_TUR: EntDailySheetTurn[];
    PLA_DIA_PAG_PRO: EntDailySheetPagPro[];
    PLA_DIA_PAG_CLI: EntDailySheetPagCli[];
    PLA_DIA_VEN_CLI: EntDailySheetVenCli[];
    PLA_DIA_PAG_CLI_DET?: EntDailySheetPagCli[];
    PLA_DIA_VEN_CLI_DET?: EntDailySheetVenCli[];
    CPL: EntCPL;
    NOM_ADM: string;
    NOM_CONT: string;
    EDITADO: boolean;
    EDITABLE: boolean;
    NOM_REA: string;
    SAL_FIN_CAJA_ANT: number;
    FILES?: { name: string, code: string, type: number }[];
    PD_SOPORTE?: EntDailySheetSupport[];
}
